/**
 * refs:
 *  - https://stackoverflow.com/a/36592176 (merge stream)
 *  - https://stackoverflow.com/a/40572663 (browser-sync not reloading) 
 */

const 
  { src, dest, watch, series, parallel } = require('gulp'),
  bookmarklet = require('gulp-bookmarklet'),
  merge = require('merge-stream'),
  concat = require('gulp-concat'),
  order = require('gulp-order'),
  browserSync = require('browser-sync').create();

// flag to append browser-sync script tag (otherwise it won't auto-reload page)
//  because htmlsingle file generated by gulp-bookmarklet doesn't include
//  a body tag, so browser-sync can't automatically append its script tag
let APPEND_BROWSER_SYNC_TAG = false;

function appendBrowserSyncTag(cb) {
  APPEND_BROWSER_SYNC_TAG = true;
  cb();
}

function build() {
  let bookmarks = src('src/*.js')
    .pipe(bookmarklet({
      format: 'htmlsingle',
      file: 'bookmarks.html'
    }));
  let styling = src('src/base/styles.html');

  let merged = merge(bookmarks, styling);

  if (APPEND_BROWSER_SYNC_TAG) {
    merged.add(src('src/base/browser-sync.html'));
  }

  return merged
    .pipe(order(['bookmarks.html', '*.html']))
    .pipe(concat('bookmarklets.html'))
    .pipe(dest('dist'));
}

function reload(cb) {
  browserSync.reload();
  cb();
}

function serve() {
  browserSync.init({
    startPath: 'bookmarklets.html',
    server: {
      baseDir: './dist/'
    }
  });
  
  watch(['./dist/**/*'], { events: ['change'] }, reload);
}

function listen() {
  watch(['./src/**/*'], { events: ['change'] }, build);
}

const devTasks = series(appendBrowserSyncTag, build, parallel(serve, listen));

exports.build = build;
exports.dev = devTasks;
exports.default = devTasks;
