name: Publish assets to GH Pages

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install artifacts
        run: npm ci

      - name: Build files
        run: |
          git checkout gh-pages
          git merge main
          npx gulp publish

      - name: Commit new assets
        run: |
          git config --local user.name ${{ github.actor }}
          git add -A
          git commit -m "Update published assets"

      - name: Push changes
        run: git push origin gh-pages